apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: storage-postgres
  name: storage-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: storage-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: postgrespassword
          image: postgres:12
          name: storage-postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: storage-db-data
      restartPolicy: Always
      volumes:
        - name: storage-db-data
          persistentVolumeClaim:
            claimName: storage-db-data
