apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-graphql-engine
  name: auth-graphql-engine
spec:
  ports:
    - name: graphql
      port: 8082
      targetPort: 8080
  selector:
    app: auth-graphql-engine
