apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-postgres
  name: auth-postgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: auth-postgres
