apiVersion: v1
kind: Service
metadata:
  labels:
    app: tokens-graphql-engine
  name: tokens-graphql-engine
spec:
  ports:
    - name: graphql
      port: 8085
      targetPort: 8080
  selector:
    app: tokens-graphql-engine
