apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apps-postgres
  name: apps-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apps-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apps-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: postgrespassword
          ports:
            - containerPort: 5432
          image: postgres:12
          name: apps-postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: apps-db-data
      restartPolicy: Always
      volumes:
        - name: apps-db-data
          persistentVolumeClaim:
            claimName: apps-db-data
