apiVersion: v1
kind: Service
metadata:
  labels:
    app: apps-postgres
  name: apps-postgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: apps-postgres
